### ISSUE TITLE
GLSLCompat.glsllib contains ';' at the end of the first few line and Android is not happe with it

### ISSUE THREAD

**Issue by nickidebruyn** [jMonkeyEngine/jmonkeyengine#2329]
While test jme3.7.0 with my android projects I found that the jme3-core/src/main/resources/Common/ShaderLib/GLSLCompat.glsllib
code contains ';' semicolons at the end of the first few lines and android is not happy with that.

Error I am experiencing:
```
ERROR: 0:11: ';' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.                                                                                                    
                                                                                                    	at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1658)
                                                                                                    	at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1685)
                                                                                                    	at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1750)
```

**Comment by stephengold** [comment]
Thanks for documenting the issue, @nickidebruyn!

**Comment by stephengold** [comment]
According to "git blame", the failing code was last modified by PR #2217, which was integrated between v3.7.0-alpha2 and v3.7.0-beta1.

@nickidebruyn Do your Android projects work with JME v3.7.0-alpha2 ?

**Comment by nickidebruyn** [comment]
I tested a few scenarios for this. I can confirm that none of the new version (v3.7.0-alpha2, v3.7.0-beta1, v3.7.0-stable) works.
I then tested again with v3.6.1 and it worked again.
After that I changed back to v3.7.0-stable and created my own local GLSLCompat.glsllib and changed the frag shader to point to that and it worked again. This is the code I removed from my local: GLSLCompat.glsllib

```
#ifdef GL_ES
  #ifdef FRAGMENT_SHADER
    precision highp float;
    precision highp int;
    precision highp sampler2DArray;
    precision highp sampler2DShadow;
    precision highp samplerCube;
    precision highp sampler3D;
    precision highp sampler2D;
    #if __VERSION__ >= 310
      precision highp sampler2DMS;
    #endif
  #endif
#endif
```

**Comment by stephengold** [comment]
Thank you for the investigation.
Based on your findings, I'm convinced PR #2061 caused the regression.
At the time (August 2023), Riccardo indicated 2061 would need to be tested on Android.
Apparently it never got such testing, and neither did JME 3.7!
I think this calls for a 3.7.1 release...

**Comment by nickidebruyn** [comment]
Agree, that is probably a good decision.
Most shaders uses that lib.

**Comment by pavly-gerges** [comment]
What's the status of this issue?

**Comment by yaRnMcDonuts** [comment]
I've never looked into the code in GLSLCompat.glsllib and unfortunately I don't have any android experience with jme, so I can't test things to feel certain enough to confidently provide a solution. 


But I'd agree with @sgold that this PR likely caused the issue: https://github.com/riccardobl/jmonkeyengine/commit/4e851bfeeb82baab9ec3102d91ecbb292ec6ee0e

I'm not particularly knowledgeable when it comes to knowing which exact fragment/vertex shader versions and features to use in each situation especially on android, but it sounds like the "precision highp" is not fully supported on android.

And, from my understanding, this code is simply trying to set the precision for each shader varType which I'm rading mixed things about whether that's even necessary.

But I think some of this info I'm reading is coming from AI, and the rest from random stack overflow posts... so I am skeptical until I can confirm this information from another source, or preferably from our own testing. 

Nonetheless, what I'm reading is saying that:

`setting precision for types other than float and int (like sampler2DArray, samplerCube, etc.) is unnecessary in most cases.

Only float and int have multiple precision levels in GLSL.

highp, mediump, and lowp only apply to floating-point and integer types.
Example: highp float, mediump int, etc.
Samplers (sampler2D, samplerCube, etc.) are not affected by precision.

Samplers are not numerical types—they are handles to textures.
The precision of texture sampling is controlled by hardware, not by GLSL precision qualifiers.
This means precision highp sampler2D; does nothing.

`


So, unless I'm mistaken, the only potentially useful code changed in GLSLCompat  in that PR is these 2 lines:

`    precision highp float;
    precision highp int;`


And it sounds like both of these highp int/float precision qualifiers should also be okay on android. And if not, then something like a (#if __VERSION__ >= 300) check around that code should prevent it from running on android devices that don't support highp int or float. But we'll have to try and find out I guess.

So to conclude, (from my limited understanding), the highp precision on non-numerical varTypes is unsupported on android, and it is unnecessary and redundant on desktop since desktop will already default to using highp for everything if supported. But android defaults to mediump or lowp when nothing is set, so I think it is still good to declare int and float as highp if the android version supports it.


Here's what I think is the best solution from my understanding thus far, feedback is greatly appreciated though: https://github.com/jMonkeyEngine/jmonkeyengine/pull/2381

**Comment by yaRnMcDonuts** [comment]
> So far, it seems that the code added recently requires a 'main()' function to be compiled as a GLSL executable. That's why we get this error:

I think this is just a case of bad error reporting from the shader. The code setting precision qualifiers is supposed to be called before the main() function (not within it). And essentially every .fragment shader has a main function(), I'd be very surprised if there was any changes that completely removed the main function()

But because it is throwing an error in code that is setting precision before the main() function, the compiler fails before it manages to compile the main function() and then the gpu tries running it and it has a half-compiled version of the shader with no main function(), hence the incorrect error reporting.

**Comment by pavly-gerges** [comment]
Alright, @nickidebruyn Could you please guide me to reproduce this issue?

**Comment by riccardobl** [comment]
can anyone with an android setup try to remove the version check from here and see if it reproduces?

```
 #ifdef GL_ES
  #ifdef FRAGMENT_SHADER
    precision highp float;
    precision highp int;
    precision highp sampler2DArray;
    precision highp sampler2DShadow;
    precision highp samplerCube;
    precision highp sampler3D;
    precision highp sampler2D;
    #if __VERSION__ >= 310
      precision highp sampler2DMS;
    #endif
  #endif
#endif
```

to

```
#ifdef GL_ES
  #ifdef FRAGMENT_SHADER
    precision highp float;
    precision highp int;
    precision highp sampler2DArray;
    precision highp sampler2DShadow;
    precision highp samplerCube;
    precision highp sampler3D;
    precision highp sampler2D;
    precision highp sampler2DMS;
  #endif
#endif
```

it might have something to do with __VERSION__ being unset for some combination of shaders + platform

**Comment by yaRnMcDonuts** [comment]
I have doubts that this error is related to the use of __VERSION__ (based on this comment from @nickidebruyn where the error went away after removing this whole code block)

> I changed back to v3.7.0-stable and created my own local GLSLCompat.glsllib and changed the frag shader to point to that and it worked again. This is the code I removed from my local: GLSLCompat.glsllib
> 
> ```
> #ifdef GL_ES
>   #ifdef FRAGMENT_SHADER
>     precision highp float;
>     precision highp int;
>     precision highp sampler2DArray;
>     precision highp sampler2DShadow;
>     precision highp samplerCube;
>     precision highp sampler3D;
>     precision highp sampler2D;
>     #if __VERSION__ >= 310
>       precision highp sampler2DMS;
>     #endif
>   #endif
> #endif
> ```

There are still other __VERSION__ checks in GLSLCompat after this code block (here is one place: https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/resources/Common/ShaderLib/GLSLCompat.glsllib#L77), so if __VERSION__ were the issue, the crash would not have been resolved from removing only this 1 instance of a version check.

After more research from yesterday, I am even more confident in my speculation that setting precision for some sampler var types is not supported on certain android devices. 



> Alright, [@nickidebruyn](https://github.com/nickidebruyn) Could you please guide me to reproduce this issue?

It should be reproducible by using any shader that imports GLSLCompat.glsllib (this includes PBRLIghting.j3md and Lighting.j3md). But there is also no guarantee that the error will be reproducible on your specific android device, because different devices/gpus will have different support for these types of things. You may have a newer device that can bypass errors that the OP's device cannot.

**Comment by riccardobl** [comment]
I don't think it is correct to say that the precision qualifiers are not needed for samplers, the opengl es docs says

>The fragment language has no default precision qualifier for floating point types. Hence for float, floating
point vector and matrix variable declarations, either the declaration must include a precision qualifier or
the default float precision must have been previously declared. Similarly, there is no default precision
qualifier for the following sampler types in either the vertex or fragment language:
sampler3D;
samplerCubeShadow;
sampler2DShadow;
sampler2DArray;
sampler2DArrayShadow;
isampler2D;
isampler3D;
isamplerCube;
isampler2DArray;
usampler2D;
usampler3D;
usamplerCube;
usampler2DArray

I have 3 theories of what might cause the issue:
1.  by considering only the error log: this could be a precompiler issues that causes it to fails to replace  `__VERSION__`  in that specific condition, for whatever reason.
2. by considering the docs:  `sampler2DMS` is not included in the list, maybe the precision qualifier doesn't have a widespread support for this sampler.
3. `sampler2DShadow` is another possible candidate since it is another special sampler

imo 2 is very likely, since it is a special sampler, is closest to the reported line and fitting with the current findings. 
But might need some trial and error by someone who can reproduce it.

**Comment by yaRnMcDonuts** [comment]
> there is no default precision
> qualifier for the following sampler types in either the vertex or fragment language:

This is the type of wording that I found confusing when I read that doc.

I wasn't sure if this wording is meant to imply that we aren't supposed to be setting default values for those samplers, or if it means that the shader internally will not have default values if they are unset. 

l'd assume that if we don't set a desired precision, that the shader or device (or something) would have to default to some precision values. Otherwise would it just have null or non existent precision? I felt like that sort of makes no sense; but again I have very little experience with this prior to reading that doc and some other random posts I found that are likely not reliable sources. 



> imo 2 is very likely, since it is a special sampler, is closest to the reported line and fitting with the current findings.
> But might need some trial and error by someone who can reproduce it.

I agree on this. I feel like I read a lot of conflicting and possibly incorrect thins from random posts around the web. But the one consistent thing I read is that some android devicse don't like when certain sampler types have their precision set.

**Comment by nickidebruyn** [comment]
I have only noticed the comments on this issue now. Sorry for not coming back earlier.
So I already have a local copy of GLSLCompat.glsllib which I can modify in my current workflow.

I also have access to a few different android devices, old and new.
There for I am will to test what ever solution or code for GLSLCompat.glsllib you want me to test.

Once we have identified the exact problem, we can merge that into the jme code.

What do you think?

**Comment by yaRnMcDonuts** [comment]
> I also have access to a few different android devices, old and new.
> There for I am will to test what ever solution or code for GLSLCompat.glsllib you want me to test.

For the most thorough testing, you could test each individual line of code in this block by iteslf:

`    precision highp float;
    precision highp int;
    precision highp sampler2DArray;
    precision highp sampler2DShadow;
    precision highp samplerCube;
    precision highp sampler3D;
    precision highp sampler2D;
    precision highp sampler2DMS;
`

And then let us know which ones cause a crash, and which are safe to use on android

So far, it is likely that `precision highp sampler2DMS;` will certainly cause the crash, and I suspect it could crash when trying to set highp on a few other sampler types.

I've also heard reports where older android devices do not like having float or int set to high precision either, so you could confirm (or disprove) this theory by testing `precision highp float;` and `precision highp int;` alone while using your oldest and most outdated android device, and also on a newer android device.

**Comment by nickidebruyn** [comment]
I played around with the different devices and emulators and doesn't seem to reproduce the error when I put that code back, I did however had to define a "lowp", seems like it was not supported on older devices.

This is what my GLSLCompat.glsllib looks like for the above settings:
```
#ifdef GL_ES
  #define lowp
  
  #ifdef FRAGMENT_SHADER
    precision highp float;
    precision highp int;
    precision highp sampler2DArray;
    precision highp sampler2DShadow;
    precision highp samplerCube;
    precision highp sampler3D;
    precision highp sampler2D;
    #if __VERSION__ >= 310
      precision highp sampler2DMS;
    #endif
  #endif
#endif
```

**Comment by yaRnMcDonuts** [comment]
I updated my PR #2381 to reflect the changes you've tested. Although i have to say I'm surprised that is what ended up being the solution to the issue. I'm curious @riccardobl if you know what's going on here.

Either way its good that the exception has gone away.

I also added an #ifndef check around the line of code defining lowp to ensure that no double declaration errors occur on devices that already have lowp declared, just in case.

Let me know if the PR looks good.

**Comment by riccardobl** [comment]
Was lowp causing the issue? 
Redefining lowp like this is dangerous, it will turn every lowp variables into default precision, that depends on shader stage and type.

What is the code that uses lowp exactly? And which android version is failing to compile it?

**Comment by riccardobl** [comment]
is this still an  issue?
